### ISSUE TITLE
Show Latest ScalaTest 3.0.5

### ISSUE THREAD

**Issue by cheeseng** [scalatest/scalatest-website#102]
ScalaTest 3.0.5 is released: 

https://github.com/scalatest/scalatest/releases/tag/release-3.0.5

We should update website to show 3.0.5 on its front page and include release note for 3.0.5.

**Comment by plinlor** [comment]
Included Chee Seng's release notes and updated relevant website pages.

https://github.com/scalatest/scalatest-website/pull/103

@cheeseng Please take a look at the older_releases and current release install instructions to make sure that all named versions will indeed cooperate.  I don't have a clear picture of which versions "play nice together".  Did most of the older_releases 3.0.4 entry as a clone from the 3.0.3 entry, which gets us most of the way there, but perhaps some tweaks are required to version numbers and which Scala versions are appropriate, by you or Bill...

**Comment by plinlor** [comment]
Merged by Bill a day ago, so I'm closing this issue.
