### ISSUE TITLE
Use normal HTML links for external links

### ISSUE THREAD

**Issue by Topperfalkon** [scalatest/scalatest-website#31]
Currently, external links seem to use a javascript call to open a new window. This behaviour can be ignored by some browsers, and makes it impossible on Firefox to open links as a new tab with a middle-mouse click.

Unless there's a specific reason for doing external links this way, it'd be better to have a normal HTML link with a target="_blank" attribute, and let the browser decide what it wants to do.

**Comment by bvenners** [comment]
@plinlor not sure that we are doing this or Scaladoc. Investigate and let me know.

**Comment by plinlor** [comment]
https://github.com/scalatest/scalatest-website/pull/82
