### ISSUE TITLE
Setting capture directory

### ISSUE THREAD

**Issue by naderghanbari** [scalatest/scalatest-website#43]
In `Using Selenium` guide (version `2.2.4`) it's mentioned that the capture directory can be set with

    capture set "someDir"

but seems that the only way to do this is using the `setCaptureDir` function:

    setCaptureDir("someDir")

so either the docs should be fixed or an alias to this function should be added to the `capture` singleton object

**Comment by cheeseng** [comment]
Hi Nader, I couldn't find the capture set "xxx" documentation, does not
seem to be in the scaladoc, do you mind pointing me to the line?

**Comment by naderghanbari** [comment]
It's not in the scaladoc, it's here:

https://github.com/scalatest/scalatest-website/blob/master/app/views/userGuide/usingSelenium.scala.html#L253

**Comment by cheeseng** [comment]
@naderghanbari i see, should be easy to add that syntax in if we want to, if @bvenners ok that  :)

**Comment by cheeseng** [comment]
@naderghanbari @bvenners for the moment i think we should change scalatest-website to use setCaptureDir, to avoid any further confusion.

**Comment by naderghanbari** [comment]
Ok, thanks.

There are also some good stuff in Selenium goodies which are not mentioned in the scalatest-website (for instance there is a `withScreenshot` which is very useful but I didn't find anything about it in the website), is it worth creating a separate issue for that one?

**Comment by cheeseng** [comment]
@naderghanbari Indeed, we'll probably need to update scalatest-website selenium page to up to date with WebBrowser scaladoc: 

http://doc.scalatest.org/2.2.4/index.html#org.scalatest.selenium.WebBrowser

I don't recall any new enhancment for selenium in the upcoming 3.0 release, so the 2.2.4 scaladoc should be the best reference now.

And thanks for reporting the wrong example on scalatest-website!

**Comment by bvenners** [comment]
Hi Nadar,

Thanks for pointing out this mistake in the documentation. I deployed a fix this morning.

Bill

**Comment by bvenners** [comment]
Oh, and I also added the mention of withScreenShot too. - Bill
