### ISSUE TITLE
front page doesn't have latest 3.0.x release

### ISSUE THREAD

**Issue by SethTisue** [scalatest/scalatest-website#57]

**Comment by SethTisue** [comment]
in a similar vein, https://www.scalatest.org/release_notes stops at 3.0.0-M15

maybe I'm not looking hard enough, but I haven't found information anywhere about the ScalaTest 3.0.1 release, which I see on Maven Central but don't see any information about elsewhere (e.g. at https://twitter.com/scalatest)

**Comment by SethTisue** [comment]
the current version is now 3.0.3, I believe, but the front page still says 3.0.1

**Comment by SethTisue** [comment]
https://www.scalatest.org/release_notes also stops at 3.0.1 now

**Comment by plinlor** [comment]
Done.  Front page reflects Version 3.0.4 now
