### ISSUE TITLE
AssertThrows doesn't exist

### ISSUE THREAD

**Issue by derrickoswald** [scalatest/scalatest-website#70]
The users guide (http://www.scalatest.org/user_guide/using_assertions) says:

_

> ScalaTest provides two methods: assertThrows and intercept.

_

yet AssertThrows is not present in the library.

**Comment by bvenners** [comment]
The website is for Scala 3.0.x. Are you perhaps using an earlier version of ScalaTest?

**Comment by bvenners** [comment]
I think this was a case of an earlier version of ScalaTest being used, but we only show documentation for the latest version of ScalaTest on scalatest.org.
