### ISSUE TITLE
List changes in 3.0.2, 3.0.3, and 3.0.4 for release notes

### ISSUE THREAD

**Issue by bvenners** [scalatest/scalatest-website#77]
Hi Chee Seng,

Please look back at the commits to refresh your memory as to what we released in each of 3.0.2, 3.0.3, and 3.0.4 and send to Peter and me so Peter can do release notes for those tomorrow.

Thanks.

Bill

**Comment by cheeseng** [comment]
Hi @bvenners @plinlor , 

I listed the release notes for 3.0.2, 3.0.3 and 3.0.4 here: 

https://github.com/scalatest/scalatest/releases

**Comment by bvenners** [comment]
tnx.
