### ISSUE TITLE
Please make a 3.1.0 release notes page that is not accessible

### ISSUE THREAD

**Issue by bvenners** [scalatest/scalatest-website#85]
Hi Peter,

From Chee Seng's list, please make a first draft of the 3.1.0 combined ScalaTest/Scalactic release notes:

https://github.com/scalatest/scalatest/issues/1218

Please don't link to it from anywhere, and in when you check it in, don't add it to the routes so no one can get to it prior to the 3.1.0 release to minimize confusion. (You'll likely want to add it to the routes while you develop it, so just take that out before you make the PR.0

Thanks.

Bill

**Comment by plinlor** [comment]
I've asked Chee Seng on the original listing-of-release-notes issue page, to clarify two phrasings (the rest look good).  https://github.com/scalatest/scalatest/issues/1218

**Comment by plinlor** [comment]
Tweaked the 3.1.0 release notes text per Chee Seng's clarifications.  It's in branch feature-add-3.1.0-releasenotes   -- but is not slated for merge quite yet.  So, closing this issue for now.
