### ISSUE TITLE
Replace ScalaUtils with Scalactic in 3.0.x release notes

### ISSUE THREAD

**Issue by bvenners** [scalatest/scalatest-website#86]
Hi Peter,

Please replace ScalaUtils with Scalactic in the releasnotes for 3.0.1, 3.0.2, 3.0.3, and 3.0.4. ScalaUtils was the original name for Scalactic, but it is not called that anymore.

Thanks.

Bill

**Comment by plinlor** [comment]
https://github.com/scalatest/scalatest-website/pull/87

**Comment by plinlor** [comment]
Hi Bill,

Please review the above PR and merge at your convenience.

Thanks,
Peter
