### ISSUE TITLE
Hide videos tab on ScalaTest website

### ISSUE THREAD

**Issue by sylee13** [scalatest/scalatest-website#88]
We'd like to hide the videos tab for now until we upload new videos: http://www.scalatest.org/videos

**Comment by plinlor** [comment]
For Bill's review/approval/merge:  https://github.com/scalatest/scalatest-website/pull/91

**Comment by bvenners** [comment]
Hi Peter please ask chee Seng to check the ScalaTest.org and scalactic.org prs while I'm teaching this week.
