### ISSUE TITLE
Fix link to supersafe user guide at scalatest.org and scalactic.org

### ISSUE THREAD

**Issue by bvenners** [scalatest/scalatest-website#90]
Hi Peter,

The following two pages link to an outdated user guide page:

http://www.scalactic.org/supersafe

http://www.scalatest.org/supersafe

They both link to:

http://www.artima.com/supersafe_user_guide_rc.html

But they should link to:

http://www.artima.com/supersafe_user_guide.html

Thanks.

Bill

**Comment by plinlor** [comment]
ScalaTest PR for this:  https://github.com/scalatest/scalatest-website/pull/92
Scalactic PR for this:  https://github.com/scalatest/scalactic-website/pull/11

**Comment by cheeseng** [comment]
@plinlor PRs looks good and merged into master, we may close this once the changes are up into production server!

Thanks.

**Comment by plinlor** [comment]
Pushed to server on Tuesday November 22, 2017.  Closing this per Chee Seng's comment above.
